apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tethys-home-pvc
  namespace: tethys-k8
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tethys-persist-pvc
  namespace: tethys-k8
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi