apiVersion: batch/v1
kind: Job
metadata:
  name: tethys-init
  namespace: tethys-k8
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: tethys-init
    spec:
      restartPolicy: Never
      containers:
        - name: tethys-init
          image: tethys-workshop:local
          imagePullPolicy: Never
          command: ["/usr/lib/tethys/init-tethys.sh"]
          env:
            - name: TETHYS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tethys-db-app
                  key: password
          envFrom:
            - configMapRef:
                name: tethys-config
            - secretRef:
                name: tethys-secret
          volumeMounts:
            - name: tethys-home
              mountPath: /usr/lib/tethys
            - name: tethys-persist
              mountPath: /var/lib/tethys_persist
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi 
      volumes:
        - name: tethys-home
          persistentVolumeClaim:
            claimName: tethys-home-pvc
        - name: tethys-persist
          persistentVolumeClaim:
            claimName: tethys-persist-pvc