apiVersion: v1
kind: Secret
metadata:
  name: tethys-secret
  namespace: tethys-k8
type: Opaque
stringData:
  PORTAL_SUPERUSER_NAME: "admin"
  PORTAL_SUPERUSER_EMAIL: "admin@example.com"
  PORTAL_SUPERUSER_PASSWORD: "pass"
  TETHYS_SECRET_KEY: "REPLACE-with-a-50-char-random-secret-key"